import { micro } from "./fonts";
import "bootstrap/dist/css/bootstrap.min.css";
import "@/styles/globals.scss";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import QueryProvider from "@/providers/QueryProvider";
import { CartProvider } from "@/context/CartContext";
// import NavSpace from '@/components/NavSpace';

export const metadata = {
  title: "ORM System",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={micro.variable}>
      <body>
        <QueryProvider>
          <CartProvider>
            <Navbar />
            {children}
            <Footer />
          </CartProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
